package com.westee.sales.generate;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CakeTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    long countByExample(CakeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int deleteByExample(CakeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int insert(CakeTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int insertSelective(CakeTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    List<CakeTag> selectByExample(CakeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    CakeTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByExampleSelective(@Param("record") CakeTag record, @Param("example") CakeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByExample(@Param("record") CakeTag record, @Param("example") CakeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByPrimaryKeySelective(CakeTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByPrimaryKey(CakeTag record);
}