package com.westee.sales.generate;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ChargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    long countByExample(ChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int deleteByExample(ChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int insert(Charge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int insertSelective(Charge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    List<Charge> selectByExample(ChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    Charge selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByExampleSelective(@Param("record") Charge record, @Param("example") ChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByExample(@Param("record") Charge record, @Param("example") ChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByPrimaryKeySelective(Charge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByPrimaryKey(Charge record);
}