package com.westee.sales.generate;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    long countByExample(DiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int deleteByExample(DiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int insert(Discount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int insertSelective(Discount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    List<Discount> selectByExample(DiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    Discount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByExampleSelective(@Param("record") Discount record, @Param("example") DiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByExample(@Param("record") Discount record, @Param("example") DiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByPrimaryKeySelective(Discount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByPrimaryKey(Discount record);
}