package com.westee.sales.generate;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ExpressInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Mon Sep 18 21:05:57 CST 2023
     */
    long countByExample(ExpressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Mon Sep 18 21:05:57 CST 2023
     */
    int deleteByExample(ExpressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Mon Sep 18 21:05:57 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Mon Sep 18 21:05:57 CST 2023
     */
    int insert(ExpressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Mon Sep 18 21:05:57 CST 2023
     */
    int insertSelective(ExpressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Mon Sep 18 21:05:57 CST 2023
     */
    List<ExpressInfo> selectByExample(ExpressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Mon Sep 18 21:05:57 CST 2023
     */
    ExpressInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Mon Sep 18 21:05:57 CST 2023
     */
    int updateByExampleSelective(@Param("record") ExpressInfo record, @Param("example") ExpressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Mon Sep 18 21:05:57 CST 2023
     */
    int updateByExample(@Param("record") ExpressInfo record, @Param("example") ExpressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Mon Sep 18 21:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(ExpressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Mon Sep 18 21:05:57 CST 2023
     */
    int updateByPrimaryKey(ExpressInfo record);
}