package com.westee.sales.generate;

import java.io.Serializable;
import java.util.Date;

public class ExpressGoodsType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPRESS_GOODS_TYPE.ID
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPRESS_GOODS_TYPE.NAME
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPRESS_GOODS_TYPE.GOODS_TYPE
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    private Integer goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPRESS_GOODS_TYPE.CREATED_AT
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPRESS_GOODS_TYPE.UPDATED_AT
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EXPRESS_GOODS_TYPE
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_GOODS_TYPE
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public ExpressGoodsType(Long id, String name, Integer goodsType, Date createdAt, Date updatedAt) {
        this.id = id;
        this.name = name;
        this.goodsType = goodsType;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_GOODS_TYPE
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public ExpressGoodsType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPRESS_GOODS_TYPE.ID
     *
     * @return the value of EXPRESS_GOODS_TYPE.ID
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPRESS_GOODS_TYPE.ID
     *
     * @param id the value for EXPRESS_GOODS_TYPE.ID
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPRESS_GOODS_TYPE.NAME
     *
     * @return the value of EXPRESS_GOODS_TYPE.NAME
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPRESS_GOODS_TYPE.NAME
     *
     * @param name the value for EXPRESS_GOODS_TYPE.NAME
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPRESS_GOODS_TYPE.GOODS_TYPE
     *
     * @return the value of EXPRESS_GOODS_TYPE.GOODS_TYPE
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public Integer getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPRESS_GOODS_TYPE.GOODS_TYPE
     *
     * @param goodsType the value for EXPRESS_GOODS_TYPE.GOODS_TYPE
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public void setGoodsType(Integer goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPRESS_GOODS_TYPE.CREATED_AT
     *
     * @return the value of EXPRESS_GOODS_TYPE.CREATED_AT
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPRESS_GOODS_TYPE.CREATED_AT
     *
     * @param createdAt the value for EXPRESS_GOODS_TYPE.CREATED_AT
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPRESS_GOODS_TYPE.UPDATED_AT
     *
     * @return the value of EXPRESS_GOODS_TYPE.UPDATED_AT
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPRESS_GOODS_TYPE.UPDATED_AT
     *
     * @param updatedAt the value for EXPRESS_GOODS_TYPE.UPDATED_AT
     *
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}