package com.westee.sales.generate;

import java.io.Serializable;
import java.util.Date;

public class GoodsTypes implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_TYPES.ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_TYPES.NAME
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_TYPES.DELETED
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_TYPES.OWNER_SHOP_ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Long ownerShopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_TYPES.CREATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_TYPES.UPDATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GOODS_TYPES
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_TYPES
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public GoodsTypes(Long id, String name, Integer deleted, Long ownerShopId, Date createdAt, Date updatedAt) {
        this.id = id;
        this.name = name;
        this.deleted = deleted;
        this.ownerShopId = ownerShopId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_TYPES
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public GoodsTypes() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_TYPES.ID
     *
     * @return the value of GOODS_TYPES.ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_TYPES.ID
     *
     * @param id the value for GOODS_TYPES.ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_TYPES.NAME
     *
     * @return the value of GOODS_TYPES.NAME
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_TYPES.NAME
     *
     * @param name the value for GOODS_TYPES.NAME
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_TYPES.DELETED
     *
     * @return the value of GOODS_TYPES.DELETED
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_TYPES.DELETED
     *
     * @param deleted the value for GOODS_TYPES.DELETED
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_TYPES.OWNER_SHOP_ID
     *
     * @return the value of GOODS_TYPES.OWNER_SHOP_ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Long getOwnerShopId() {
        return ownerShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_TYPES.OWNER_SHOP_ID
     *
     * @param ownerShopId the value for GOODS_TYPES.OWNER_SHOP_ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setOwnerShopId(Long ownerShopId) {
        this.ownerShopId = ownerShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_TYPES.CREATED_AT
     *
     * @return the value of GOODS_TYPES.CREATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_TYPES.CREATED_AT
     *
     * @param createdAt the value for GOODS_TYPES.CREATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_TYPES.UPDATED_AT
     *
     * @return the value of GOODS_TYPES.UPDATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_TYPES.UPDATED_AT
     *
     * @param updatedAt the value for GOODS_TYPES.UPDATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}