package com.westee.sales.generate;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Tue Nov 28 21:32:35 CST 2023
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Tue Nov 28 21:32:35 CST 2023
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Tue Nov 28 21:32:35 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Tue Nov 28 21:32:35 CST 2023
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Tue Nov 28 21:32:35 CST 2023
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Tue Nov 28 21:32:35 CST 2023
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Tue Nov 28 21:32:35 CST 2023
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Tue Nov 28 21:32:35 CST 2023
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Tue Nov 28 21:32:35 CST 2023
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Tue Nov 28 21:32:35 CST 2023
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Tue Nov 28 21:32:35 CST 2023
     */
    int updateByPrimaryKey(Role record);
}