package com.westee.sales.generate;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SwiperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    long countByExample(SwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    int deleteByExample(SwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    int insert(Swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    int insertSelective(Swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    List<Swiper> selectByExample(SwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    Swiper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    int updateByExampleSelective(@Param("record") Swiper record, @Param("example") SwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    int updateByExample(@Param("record") Swiper record, @Param("example") SwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    int updateByPrimaryKeySelective(Swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    int updateByPrimaryKey(Swiper record);
}