package com.westee.sales.generate;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WxExpressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    public WxExpressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andErrcodeIsNull() {
            addCriterion("ERRCODE is null");
            return (Criteria) this;
        }

        public Criteria andErrcodeIsNotNull() {
            addCriterion("ERRCODE is not null");
            return (Criteria) this;
        }

        public Criteria andErrcodeEqualTo(Integer value) {
            addCriterion("ERRCODE =", value, "errcode");
            return (Criteria) this;
        }

        public Criteria andErrcodeNotEqualTo(Integer value) {
            addCriterion("ERRCODE <>", value, "errcode");
            return (Criteria) this;
        }

        public Criteria andErrcodeGreaterThan(Integer value) {
            addCriterion("ERRCODE >", value, "errcode");
            return (Criteria) this;
        }

        public Criteria andErrcodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ERRCODE >=", value, "errcode");
            return (Criteria) this;
        }

        public Criteria andErrcodeLessThan(Integer value) {
            addCriterion("ERRCODE <", value, "errcode");
            return (Criteria) this;
        }

        public Criteria andErrcodeLessThanOrEqualTo(Integer value) {
            addCriterion("ERRCODE <=", value, "errcode");
            return (Criteria) this;
        }

        public Criteria andErrcodeIn(List<Integer> values) {
            addCriterion("ERRCODE in", values, "errcode");
            return (Criteria) this;
        }

        public Criteria andErrcodeNotIn(List<Integer> values) {
            addCriterion("ERRCODE not in", values, "errcode");
            return (Criteria) this;
        }

        public Criteria andErrcodeBetween(Integer value1, Integer value2) {
            addCriterion("ERRCODE between", value1, value2, "errcode");
            return (Criteria) this;
        }

        public Criteria andErrcodeNotBetween(Integer value1, Integer value2) {
            addCriterion("ERRCODE not between", value1, value2, "errcode");
            return (Criteria) this;
        }

        public Criteria andErrmsgIsNull() {
            addCriterion("ERRMSG is null");
            return (Criteria) this;
        }

        public Criteria andErrmsgIsNotNull() {
            addCriterion("ERRMSG is not null");
            return (Criteria) this;
        }

        public Criteria andErrmsgEqualTo(String value) {
            addCriterion("ERRMSG =", value, "errmsg");
            return (Criteria) this;
        }

        public Criteria andErrmsgNotEqualTo(String value) {
            addCriterion("ERRMSG <>", value, "errmsg");
            return (Criteria) this;
        }

        public Criteria andErrmsgGreaterThan(String value) {
            addCriterion("ERRMSG >", value, "errmsg");
            return (Criteria) this;
        }

        public Criteria andErrmsgGreaterThanOrEqualTo(String value) {
            addCriterion("ERRMSG >=", value, "errmsg");
            return (Criteria) this;
        }

        public Criteria andErrmsgLessThan(String value) {
            addCriterion("ERRMSG <", value, "errmsg");
            return (Criteria) this;
        }

        public Criteria andErrmsgLessThanOrEqualTo(String value) {
            addCriterion("ERRMSG <=", value, "errmsg");
            return (Criteria) this;
        }

        public Criteria andErrmsgLike(String value) {
            addCriterion("ERRMSG like", value, "errmsg");
            return (Criteria) this;
        }

        public Criteria andErrmsgNotLike(String value) {
            addCriterion("ERRMSG not like", value, "errmsg");
            return (Criteria) this;
        }

        public Criteria andErrmsgIn(List<String> values) {
            addCriterion("ERRMSG in", values, "errmsg");
            return (Criteria) this;
        }

        public Criteria andErrmsgNotIn(List<String> values) {
            addCriterion("ERRMSG not in", values, "errmsg");
            return (Criteria) this;
        }

        public Criteria andErrmsgBetween(String value1, String value2) {
            addCriterion("ERRMSG between", value1, value2, "errmsg");
            return (Criteria) this;
        }

        public Criteria andErrmsgNotBetween(String value1, String value2) {
            addCriterion("ERRMSG not between", value1, value2, "errmsg");
            return (Criteria) this;
        }

        public Criteria andAppidIsNull() {
            addCriterion("APPID is null");
            return (Criteria) this;
        }

        public Criteria andAppidIsNotNull() {
            addCriterion("APPID is not null");
            return (Criteria) this;
        }

        public Criteria andAppidEqualTo(String value) {
            addCriterion("APPID =", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotEqualTo(String value) {
            addCriterion("APPID <>", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThan(String value) {
            addCriterion("APPID >", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThanOrEqualTo(String value) {
            addCriterion("APPID >=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThan(String value) {
            addCriterion("APPID <", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThanOrEqualTo(String value) {
            addCriterion("APPID <=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLike(String value) {
            addCriterion("APPID like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotLike(String value) {
            addCriterion("APPID not like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidIn(List<String> values) {
            addCriterion("APPID in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotIn(List<String> values) {
            addCriterion("APPID not in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidBetween(String value1, String value2) {
            addCriterion("APPID between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotBetween(String value1, String value2) {
            addCriterion("APPID not between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdIsNull() {
            addCriterion("WX_STORE_ID is null");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdIsNotNull() {
            addCriterion("WX_STORE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdEqualTo(String value) {
            addCriterion("WX_STORE_ID =", value, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdNotEqualTo(String value) {
            addCriterion("WX_STORE_ID <>", value, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdGreaterThan(String value) {
            addCriterion("WX_STORE_ID >", value, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdGreaterThanOrEqualTo(String value) {
            addCriterion("WX_STORE_ID >=", value, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdLessThan(String value) {
            addCriterion("WX_STORE_ID <", value, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdLessThanOrEqualTo(String value) {
            addCriterion("WX_STORE_ID <=", value, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdLike(String value) {
            addCriterion("WX_STORE_ID like", value, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdNotLike(String value) {
            addCriterion("WX_STORE_ID not like", value, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdIn(List<String> values) {
            addCriterion("WX_STORE_ID in", values, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdNotIn(List<String> values) {
            addCriterion("WX_STORE_ID not in", values, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdBetween(String value1, String value2) {
            addCriterion("WX_STORE_ID between", value1, value2, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxStoreIdNotBetween(String value1, String value2) {
            addCriterion("WX_STORE_ID not between", value1, value2, "wxStoreId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdIsNull() {
            addCriterion("WX_ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdIsNotNull() {
            addCriterion("WX_ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdEqualTo(String value) {
            addCriterion("WX_ORDER_ID =", value, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdNotEqualTo(String value) {
            addCriterion("WX_ORDER_ID <>", value, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdGreaterThan(String value) {
            addCriterion("WX_ORDER_ID >", value, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("WX_ORDER_ID >=", value, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdLessThan(String value) {
            addCriterion("WX_ORDER_ID <", value, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdLessThanOrEqualTo(String value) {
            addCriterion("WX_ORDER_ID <=", value, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdLike(String value) {
            addCriterion("WX_ORDER_ID like", value, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdNotLike(String value) {
            addCriterion("WX_ORDER_ID not like", value, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdIn(List<String> values) {
            addCriterion("WX_ORDER_ID in", values, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdNotIn(List<String> values) {
            addCriterion("WX_ORDER_ID not in", values, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdBetween(String value1, String value2) {
            addCriterion("WX_ORDER_ID between", value1, value2, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andWxOrderIdNotBetween(String value1, String value2) {
            addCriterion("WX_ORDER_ID not between", value1, value2, "wxOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdIsNull() {
            addCriterion("STORE_ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdIsNotNull() {
            addCriterion("STORE_ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdEqualTo(String value) {
            addCriterion("STORE_ORDER_ID =", value, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdNotEqualTo(String value) {
            addCriterion("STORE_ORDER_ID <>", value, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdGreaterThan(String value) {
            addCriterion("STORE_ORDER_ID >", value, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_ORDER_ID >=", value, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdLessThan(String value) {
            addCriterion("STORE_ORDER_ID <", value, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdLessThanOrEqualTo(String value) {
            addCriterion("STORE_ORDER_ID <=", value, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdLike(String value) {
            addCriterion("STORE_ORDER_ID like", value, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdNotLike(String value) {
            addCriterion("STORE_ORDER_ID not like", value, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdIn(List<String> values) {
            addCriterion("STORE_ORDER_ID in", values, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdNotIn(List<String> values) {
            addCriterion("STORE_ORDER_ID not in", values, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdBetween(String value1, String value2) {
            addCriterion("STORE_ORDER_ID between", value1, value2, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andStoreOrderIdNotBetween(String value1, String value2) {
            addCriterion("STORE_ORDER_ID not between", value1, value2, "storeOrderId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdIsNull() {
            addCriterion("SERVICE_TRANS_ID is null");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdIsNotNull() {
            addCriterion("SERVICE_TRANS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdEqualTo(String value) {
            addCriterion("SERVICE_TRANS_ID =", value, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdNotEqualTo(String value) {
            addCriterion("SERVICE_TRANS_ID <>", value, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdGreaterThan(String value) {
            addCriterion("SERVICE_TRANS_ID >", value, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdGreaterThanOrEqualTo(String value) {
            addCriterion("SERVICE_TRANS_ID >=", value, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdLessThan(String value) {
            addCriterion("SERVICE_TRANS_ID <", value, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdLessThanOrEqualTo(String value) {
            addCriterion("SERVICE_TRANS_ID <=", value, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdLike(String value) {
            addCriterion("SERVICE_TRANS_ID like", value, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdNotLike(String value) {
            addCriterion("SERVICE_TRANS_ID not like", value, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdIn(List<String> values) {
            addCriterion("SERVICE_TRANS_ID in", values, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdNotIn(List<String> values) {
            addCriterion("SERVICE_TRANS_ID not in", values, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdBetween(String value1, String value2) {
            addCriterion("SERVICE_TRANS_ID between", value1, value2, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andServiceTransIdNotBetween(String value1, String value2) {
            addCriterion("SERVICE_TRANS_ID not between", value1, value2, "serviceTransId");
            return (Criteria) this;
        }

        public Criteria andDistanceIsNull() {
            addCriterion("DISTANCE is null");
            return (Criteria) this;
        }

        public Criteria andDistanceIsNotNull() {
            addCriterion("DISTANCE is not null");
            return (Criteria) this;
        }

        public Criteria andDistanceEqualTo(Integer value) {
            addCriterion("DISTANCE =", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotEqualTo(Integer value) {
            addCriterion("DISTANCE <>", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceGreaterThan(Integer value) {
            addCriterion("DISTANCE >", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceGreaterThanOrEqualTo(Integer value) {
            addCriterion("DISTANCE >=", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLessThan(Integer value) {
            addCriterion("DISTANCE <", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLessThanOrEqualTo(Integer value) {
            addCriterion("DISTANCE <=", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceIn(List<Integer> values) {
            addCriterion("DISTANCE in", values, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotIn(List<Integer> values) {
            addCriterion("DISTANCE not in", values, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceBetween(Integer value1, Integer value2) {
            addCriterion("DISTANCE between", value1, value2, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotBetween(Integer value1, Integer value2) {
            addCriterion("DISTANCE not between", value1, value2, "distance");
            return (Criteria) this;
        }

        public Criteria andFeeIsNull() {
            addCriterion("FEE is null");
            return (Criteria) this;
        }

        public Criteria andFeeIsNotNull() {
            addCriterion("FEE is not null");
            return (Criteria) this;
        }

        public Criteria andFeeEqualTo(Integer value) {
            addCriterion("FEE =", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotEqualTo(Integer value) {
            addCriterion("FEE <>", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThan(Integer value) {
            addCriterion("FEE >", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("FEE >=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThan(Integer value) {
            addCriterion("FEE <", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThanOrEqualTo(Integer value) {
            addCriterion("FEE <=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeIn(List<Integer> values) {
            addCriterion("FEE in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotIn(List<Integer> values) {
            addCriterion("FEE not in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeBetween(Integer value1, Integer value2) {
            addCriterion("FEE between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("FEE not between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdIsNull() {
            addCriterion("TRANS_ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdIsNotNull() {
            addCriterion("TRANS_ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdEqualTo(String value) {
            addCriterion("TRANS_ORDER_ID =", value, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdNotEqualTo(String value) {
            addCriterion("TRANS_ORDER_ID <>", value, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdGreaterThan(String value) {
            addCriterion("TRANS_ORDER_ID >", value, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("TRANS_ORDER_ID >=", value, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdLessThan(String value) {
            addCriterion("TRANS_ORDER_ID <", value, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdLessThanOrEqualTo(String value) {
            addCriterion("TRANS_ORDER_ID <=", value, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdLike(String value) {
            addCriterion("TRANS_ORDER_ID like", value, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdNotLike(String value) {
            addCriterion("TRANS_ORDER_ID not like", value, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdIn(List<String> values) {
            addCriterion("TRANS_ORDER_ID in", values, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdNotIn(List<String> values) {
            addCriterion("TRANS_ORDER_ID not in", values, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdBetween(String value1, String value2) {
            addCriterion("TRANS_ORDER_ID between", value1, value2, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andTransOrderIdNotBetween(String value1, String value2) {
            addCriterion("TRANS_ORDER_ID not between", value1, value2, "transOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("ORDER_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("ORDER_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(String value) {
            addCriterion("ORDER_STATUS =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(String value) {
            addCriterion("ORDER_STATUS <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(String value) {
            addCriterion("ORDER_STATUS >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_STATUS >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(String value) {
            addCriterion("ORDER_STATUS <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(String value) {
            addCriterion("ORDER_STATUS <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLike(String value) {
            addCriterion("ORDER_STATUS like", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotLike(String value) {
            addCriterion("ORDER_STATUS not like", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<String> values) {
            addCriterion("ORDER_STATUS in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<String> values) {
            addCriterion("ORDER_STATUS not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(String value1, String value2) {
            addCriterion("ORDER_STATUS between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(String value1, String value2) {
            addCriterion("ORDER_STATUS not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("CREATED_AT is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("CREATED_AT is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("CREATED_AT =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("CREATED_AT <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("CREATED_AT >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_AT >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("CREATED_AT <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_AT <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("CREATED_AT in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("CREATED_AT not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("CREATED_AT between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_AT not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("UPDATED_AT is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("UPDATED_AT is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("UPDATED_AT =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("UPDATED_AT <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("UPDATED_AT >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED_AT >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("UPDATED_AT <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED_AT <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("UPDATED_AT in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("UPDATED_AT not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("UPDATED_AT between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED_AT not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 14 13:00:52 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}