package com.westee.cake.generate;

import com.westee.cake.generate.Cake;
import com.westee.cake.generate.CakeExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CakeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    long countByExample(CakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int deleteByExample(CakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int insert(Cake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int insertSelective(Cake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    List<Cake> selectByExample(CakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    Cake selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByExampleSelective(@Param("record") Cake record, @Param("example") CakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByExample(@Param("record") Cake record, @Param("example") CakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByPrimaryKeySelective(Cake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByPrimaryKey(Cake record);
}