package com.westee.cake.generate;

import com.westee.cake.generate.CakeTagMapping;
import com.westee.cake.generate.CakeTagMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CakeTagMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    long countByExample(CakeTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int deleteByExample(CakeTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int insert(CakeTagMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int insertSelective(CakeTagMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    List<CakeTagMapping> selectByExample(CakeTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    CakeTagMapping selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByExampleSelective(@Param("record") CakeTagMapping record, @Param("example") CakeTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByExample(@Param("record") CakeTagMapping record, @Param("example") CakeTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByPrimaryKeySelective(CakeTagMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    int updateByPrimaryKey(CakeTagMapping record);
}