package com.westee.cake.generate;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ChargeOption implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_OPTION.ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_OPTION.NAME
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_OPTION.AMOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_OPTION.GIFT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private BigDecimal gift;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_OPTION.DELETED
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_OPTION.OWNER_USR_ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Long ownerUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_OPTION.SHOP_ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_OPTION.CREATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE_OPTION.UPDATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public ChargeOption(Integer id, String name, BigDecimal amount, BigDecimal gift, Boolean deleted, Long ownerUsrId, Long shopId, Date createdAt, Date updatedAt) {
        this.id = id;
        this.name = name;
        this.amount = amount;
        this.gift = gift;
        this.deleted = deleted;
        this.ownerUsrId = ownerUsrId;
        this.shopId = shopId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public ChargeOption() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_OPTION.ID
     *
     * @return the value of CHARGE_OPTION.ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_OPTION.ID
     *
     * @param id the value for CHARGE_OPTION.ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_OPTION.NAME
     *
     * @return the value of CHARGE_OPTION.NAME
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_OPTION.NAME
     *
     * @param name the value for CHARGE_OPTION.NAME
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_OPTION.AMOUNT
     *
     * @return the value of CHARGE_OPTION.AMOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_OPTION.AMOUNT
     *
     * @param amount the value for CHARGE_OPTION.AMOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_OPTION.GIFT
     *
     * @return the value of CHARGE_OPTION.GIFT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public BigDecimal getGift() {
        return gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_OPTION.GIFT
     *
     * @param gift the value for CHARGE_OPTION.GIFT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setGift(BigDecimal gift) {
        this.gift = gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_OPTION.DELETED
     *
     * @return the value of CHARGE_OPTION.DELETED
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_OPTION.DELETED
     *
     * @param deleted the value for CHARGE_OPTION.DELETED
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_OPTION.OWNER_USR_ID
     *
     * @return the value of CHARGE_OPTION.OWNER_USR_ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Long getOwnerUsrId() {
        return ownerUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_OPTION.OWNER_USR_ID
     *
     * @param ownerUsrId the value for CHARGE_OPTION.OWNER_USR_ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setOwnerUsrId(Long ownerUsrId) {
        this.ownerUsrId = ownerUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_OPTION.SHOP_ID
     *
     * @return the value of CHARGE_OPTION.SHOP_ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_OPTION.SHOP_ID
     *
     * @param shopId the value for CHARGE_OPTION.SHOP_ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_OPTION.CREATED_AT
     *
     * @return the value of CHARGE_OPTION.CREATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_OPTION.CREATED_AT
     *
     * @param createdAt the value for CHARGE_OPTION.CREATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE_OPTION.UPDATED_AT
     *
     * @return the value of CHARGE_OPTION.UPDATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE_OPTION.UPDATED_AT
     *
     * @param updatedAt the value for CHARGE_OPTION.UPDATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}