package com.westee.cake.generate;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Coupon implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPON.ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPON.NAME
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPON.DISCOUNT_TYPE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private String discountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPON.DISCOUNT_AMOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private BigDecimal discountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPON.MINIMUM_AMOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private BigDecimal minimumAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPON.START_DATE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPON.END_DATE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPON.DISCOUNT_PERCENTAGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private BigDecimal discountPercentage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPON.DESCRIPTION
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPON.CREATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPON.UPDATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COUPON
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Coupon(Long id, String name, String discountType, BigDecimal discountAmount, BigDecimal minimumAmount, Date startDate, Date endDate, BigDecimal discountPercentage, String description, Date createdAt, Date updatedAt) {
        this.id = id;
        this.name = name;
        this.discountType = discountType;
        this.discountAmount = discountAmount;
        this.minimumAmount = minimumAmount;
        this.startDate = startDate;
        this.endDate = endDate;
        this.discountPercentage = discountPercentage;
        this.description = description;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Coupon() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPON.ID
     *
     * @return the value of COUPON.ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPON.ID
     *
     * @param id the value for COUPON.ID
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPON.NAME
     *
     * @return the value of COUPON.NAME
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPON.NAME
     *
     * @param name the value for COUPON.NAME
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPON.DISCOUNT_TYPE
     *
     * @return the value of COUPON.DISCOUNT_TYPE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public String getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPON.DISCOUNT_TYPE
     *
     * @param discountType the value for COUPON.DISCOUNT_TYPE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setDiscountType(String discountType) {
        this.discountType = discountType == null ? null : discountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPON.DISCOUNT_AMOUNT
     *
     * @return the value of COUPON.DISCOUNT_AMOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPON.DISCOUNT_AMOUNT
     *
     * @param discountAmount the value for COUPON.DISCOUNT_AMOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPON.MINIMUM_AMOUNT
     *
     * @return the value of COUPON.MINIMUM_AMOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public BigDecimal getMinimumAmount() {
        return minimumAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPON.MINIMUM_AMOUNT
     *
     * @param minimumAmount the value for COUPON.MINIMUM_AMOUNT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setMinimumAmount(BigDecimal minimumAmount) {
        this.minimumAmount = minimumAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPON.START_DATE
     *
     * @return the value of COUPON.START_DATE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPON.START_DATE
     *
     * @param startDate the value for COUPON.START_DATE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPON.END_DATE
     *
     * @return the value of COUPON.END_DATE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPON.END_DATE
     *
     * @param endDate the value for COUPON.END_DATE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPON.DISCOUNT_PERCENTAGE
     *
     * @return the value of COUPON.DISCOUNT_PERCENTAGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public BigDecimal getDiscountPercentage() {
        return discountPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPON.DISCOUNT_PERCENTAGE
     *
     * @param discountPercentage the value for COUPON.DISCOUNT_PERCENTAGE
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setDiscountPercentage(BigDecimal discountPercentage) {
        this.discountPercentage = discountPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPON.DESCRIPTION
     *
     * @return the value of COUPON.DESCRIPTION
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPON.DESCRIPTION
     *
     * @param description the value for COUPON.DESCRIPTION
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPON.CREATED_AT
     *
     * @return the value of COUPON.CREATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPON.CREATED_AT
     *
     * @param createdAt the value for COUPON.CREATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPON.UPDATED_AT
     *
     * @return the value of COUPON.UPDATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPON.UPDATED_AT
     *
     * @param updatedAt the value for COUPON.UPDATED_AT
     *
     * @mbg.generated Tue Aug 01 22:05:43 CST 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}