package com.westee.cake.generate;

import java.io.Serializable;
import java.util.Date;

public class Swiper implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWIPER.ID
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWIPER.TITLE
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWIPER.IMAGE_URL
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWIPER.SWIPER_TYPE
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    private String swiperType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWIPER.LINK_URL
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWIPER.SORT_ORDER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWIPER.ENABLED
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWIPER.CREATED_AT
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWIPER.UPDATED_AT
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public Swiper(Integer id, String title, String imageUrl, String swiperType, String linkUrl, Integer sortOrder, Boolean enabled, Date createdAt, Date updatedAt) {
        this.id = id;
        this.title = title;
        this.imageUrl = imageUrl;
        this.swiperType = swiperType;
        this.linkUrl = linkUrl;
        this.sortOrder = sortOrder;
        this.enabled = enabled;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWIPER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public Swiper() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIPER.ID
     *
     * @return the value of SWIPER.ID
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIPER.ID
     *
     * @param id the value for SWIPER.ID
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIPER.TITLE
     *
     * @return the value of SWIPER.TITLE
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIPER.TITLE
     *
     * @param title the value for SWIPER.TITLE
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIPER.IMAGE_URL
     *
     * @return the value of SWIPER.IMAGE_URL
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIPER.IMAGE_URL
     *
     * @param imageUrl the value for SWIPER.IMAGE_URL
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIPER.SWIPER_TYPE
     *
     * @return the value of SWIPER.SWIPER_TYPE
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public String getSwiperType() {
        return swiperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIPER.SWIPER_TYPE
     *
     * @param swiperType the value for SWIPER.SWIPER_TYPE
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public void setSwiperType(String swiperType) {
        this.swiperType = swiperType == null ? null : swiperType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIPER.LINK_URL
     *
     * @return the value of SWIPER.LINK_URL
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIPER.LINK_URL
     *
     * @param linkUrl the value for SWIPER.LINK_URL
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIPER.SORT_ORDER
     *
     * @return the value of SWIPER.SORT_ORDER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIPER.SORT_ORDER
     *
     * @param sortOrder the value for SWIPER.SORT_ORDER
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIPER.ENABLED
     *
     * @return the value of SWIPER.ENABLED
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIPER.ENABLED
     *
     * @param enabled the value for SWIPER.ENABLED
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIPER.CREATED_AT
     *
     * @return the value of SWIPER.CREATED_AT
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIPER.CREATED_AT
     *
     * @param createdAt the value for SWIPER.CREATED_AT
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIPER.UPDATED_AT
     *
     * @return the value of SWIPER.UPDATED_AT
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIPER.UPDATED_AT
     *
     * @param updatedAt the value for SWIPER.UPDATED_AT
     *
     * @mbg.generated Wed Aug 02 00:01:06 CST 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}