package com.westee.cake.generate;

import com.westee.cake.generate.UserCoupon;
import com.westee.cake.generate.UserCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Tue Aug 01 23:47:35 CST 2023
     */
    long countByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Tue Aug 01 23:47:35 CST 2023
     */
    int deleteByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Tue Aug 01 23:47:35 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Tue Aug 01 23:47:35 CST 2023
     */
    int insert(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Tue Aug 01 23:47:35 CST 2023
     */
    int insertSelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Tue Aug 01 23:47:35 CST 2023
     */
    List<UserCoupon> selectByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Tue Aug 01 23:47:35 CST 2023
     */
    UserCoupon selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Tue Aug 01 23:47:35 CST 2023
     */
    int updateByExampleSelective(@Param("record") UserCoupon record, @Param("example") UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Tue Aug 01 23:47:35 CST 2023
     */
    int updateByExample(@Param("record") UserCoupon record, @Param("example") UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Tue Aug 01 23:47:35 CST 2023
     */
    int updateByPrimaryKeySelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Tue Aug 01 23:47:35 CST 2023
     */
    int updateByPrimaryKey(UserCoupon record);
}