package com.westee.cake.generate;

import com.westee.cake.generate.WxExpress;
import com.westee.cake.generate.WxExpressExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WxExpressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    long countByExample(WxExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    int deleteByExample(WxExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    int insert(WxExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    int insertSelective(WxExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    List<WxExpress> selectByExample(WxExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    WxExpress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    int updateByExampleSelective(@Param("record") WxExpress record, @Param("example") WxExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    int updateByExample(@Param("record") WxExpress record, @Param("example") WxExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    int updateByPrimaryKeySelective(WxExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Sep 14 13:00:52 CST 2023
     */
    int updateByPrimaryKey(WxExpress record);
}