server:
  port: 8080

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sales?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    name: myDS

  jackson:
    time-zone: GMT+8

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

pagehelper:
  auto-dialect: true
  close-conn: true
  reasonable: false
  default-count: true

sa-token:
  token-name: satoken
  jwt-secret-key: sales-jwt