package com.westee.cake.entity;

import com.westee.cake.generate.Goods;

import java.util.List;

public class GoodsWithImages extends Goods {
    List<String> images;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Thu May 25 17:00:36 CST 2023
     */
    public GoodsWithImages() {
    }

    public List<String> getImages() {
        return images;
    }

    public void setImages(List<String> images) {
        this.images = images;
    }
}
