CREATE TABLE ROLES
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME        varchar(10),
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO ROLES (ID, NAME)
VALUES (1, 'admin');
INSERT INTO ROLES (ID, NAME)
VALUES (2, 'normal');